
name: Node.js CI runner
# runner - a hosted virtual OS for the test and bu

# workflow: the instructions defined in this file


on: # event: trigger by the repo that executes the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-deploy: # was build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    # https://github.com/actions/setup-node
    steps:
      # action - an element of a step
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: yarn install
    #- name: check env var
    #  env:
    #    TEST_ENV_VARIABLE: ${{ secrets.TEST_ENV_VARIABLE }}
    #  run: echo $TEST_ENV_VARIABLE # note: Web UI masks the value of the env var with ***
    - name: test
      env:
        TEST_ENV_VARIABLE: ${{ secrets.TEST_ENV_VARIABLE }}
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      run: yarn test
    - name: "Add remote"
      run: |
        git remote add ${{ secrets.HEROKU_APP_NAME }} https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: "Push to heroku"
      shell: "bash"
      run: |
        git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:master  

# note to skip devDependencies pruning: heroku config:set YARN_PRODUCTION=false
# note remember 'heroku logs' can show old logs at the top at the top .. use --tail and read from the bottom upwards
# next: get working from Github Actions, can't heroku git:remote because of the acceptance form ..
#       is it recognizing the command as from me, need to login somehow or .netrc file does it?
#       then cron schedule

  
        


