
name: Node.js CI runner
# runner - a hosted virtual OS for the test and bu

# workflow: the instructions defined in this file


on: # event: trigger by the repo that executes the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-deploy: # was build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    # https://github.com/actions/setup-node
    steps:
      # action - an element of a step
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: yarn install
    #- name: check env var
    #  env:
    #    TEST_ENV_VARIABLE: ${{ secrets.TEST_ENV_VARIABLE }}
    #  run: echo $TEST_ENV_VARIABLE # note: Web UI masks the value of the env var with ***
    - name: test
      env:
        TEST_ENV_VARIABLE: ${{ secrets.TEST_ENV_VARIABLE }}
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      run: yarn test
    - name: "Add remote"
      run: |
        git remote add ${{ secrets.HEROKU_APP_NAME }} https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: "fetch to unshallow"
      # without this step:
      # with a brand new Heroku app:
      #   push rejected, source repository is a shallow clone
      #   unshallow it with `git fetch --all --unshallow` to unshallow from Github
      #   try pushing again 
      # with an existing Heroku app that has already been pushed to:
      #   Run git push ***git.heroku.com/***.git HEAD:master  
      #   git push ***git.heroku.com/***.git HEAD:master  
      #   shell: /bin/bash -e {0}
      #   To https://git.heroku.com/***.git
      #   ! [rejected]        HEAD -> master (fetch first)
      #   error: failed to push some refs to 'https://git.heroku.com/***.git'
      #   hint: Updates were rejected because the remote contains work that you do
      #   hint: not have locally. This is usually caused by another repository pushing
      #   hint: to the same ref. You may want to first integrate the remote changes
      #   hint: (e.g., 'git pull ...') before pushing again.
      #   hint: See the 'Note about fast-forwards' in 'git push --help' for details.
      run: |
        git fetch --unshallow
    - name: "Push to heroku"
      run: |
        git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:master  

# note to skip devDependencies pruning: heroku config:set YARN_PRODUCTION=false
# note remember 'heroku logs' can show old logs at the top at the top .. use --tail and read from the bottom upwards
# next: get working from Github Actions, can't heroku git:remote because of the acceptance form ..
#       is it recognizing the command as from me, need to login somehow or .netrc file does it?
#       then cron schedule

#bnext: the new -y app didn't work? it won't accept the push
 #     maybe try a git pull
