
name: Node.js CI runner
# runner - a hosted virtual OS for the test and bu

# workflow: the instructions defined in this file


on: # event: trigger by the repo that executes the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-and-deploy: # was build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    # https://github.com/actions/setup-node
    steps:
      # action - an element of a step
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: yarn install
    #- name: check env var
    #  env:
    #    TEST_ENV_VARIABLE: ${{ secrets.TEST_ENV_VARIABLE }}
    #  run: echo $TEST_ENV_VARIABLE # note: Web UI masks the value of the env var with ***
    - name: test
      env:
        TEST_ENV_VARIABLE: ${{ secrets.TEST_ENV_VARIABLE }}
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
      run: yarn test
    - name: "Create .netrc for Heroku Auth"
      # 'authenticating Heroku' at https://www.smashingmagazine.com/2020/10/handling-continuous-integration-delivery-github-actions/
      # using the Auth Token method: https://devcenter.heroku.com/articles/authentication#retrieving-the-api-token
      # heroku authorizations:create provides a long-term token which is stored in github secrets as HEROKU_AUTH_TOKEN
      shell: bash
      env:
        EMAIL: ${{ secrets.EMAIL }}
        HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
      run: |
        `cat >~/.netrc <<EOF
        machine api.heroku.com
            login $HEROKU_LOGIN_EMAIL
            password $HEROKU_AUTH_TOKEN
        machine git.heroku.com
            login $HEROKU_LOGIN_EMAIL
            password $HEROKU_AUTH_TOKEN
        EOF`
    - name: test .netrc
      env:
        TEST_ENV_VARIABLE: ${{ secrets.TEST_ENV_VARIABLE }}
      run: cat .netrc
    - name: "Add remote"
      shell: "bash"
      # run this once in local repo. returns: set git remote heroku to https://git.heroku.com/data-api-z.git
      run: |
        heroku git:remote --app data-api-z
    - name: "Push to heroku"
      shell: "bash"
      run: |
        git push heroku HEAD:master  
# note to skip devDependencies pruning: heroku config:set YARN_PRODUCTION=false
# note remember 'heroku logs' can show old logs at the top at the top .. use --tail and read from the bottom upwards
# next: get working from Github Actions, can't heroku git:remote because of the acceptance form ..
#       is it recognizing the command as from me, need to login somehow or .netrc file does it?
#       then cron schedule